AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nimo-test-exercise

  Nimo Test Exercise contains two serverless microservices to query cryptocurrency prices and query search history!
  
Globals:
  Function:
    Timeout: 3

Resources:
  CryptocurrencyPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cryptocurrency-price-service/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      Events:
        CryptocurrencyPriceEvent:
          Type: Api
          Properties:
            Path: /prices
            Method: get
          Environment:
            Variables:
              API_ENV: dev

Outputs:
  CryptocurrencyPriceApi:
    Description: "API Gateway endpoint URL for dev cryptocurrency price function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/prices/"
  CryptocurrencyPriceFunction:
    Description: "Cryptocurrency price function ARN"
    Value: !GetAtt CryptocurrencyPriceFunction.Arn
  CryptocurrencyPriceFunctionIamRole:
    Description: "Implicit IAM Role created for cryptocurrency price function"
    Value: !GetAtt CryptocurrencyPriceFunctionRole.Arn
